spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/practices?useSSL=false
    username: root
    password: zzz13140.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: warn
    cn.edu.lzzy.mypractices: debug
  file:
    name: blog-dev.log
server:
  port: 8080

swagger:
  enabled: true



